//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATLANEntities : DbContext
    {
        public ATLANEntities()
            : base("name=ATLANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ST_CLIENT_TABLE_SYNC> ST_CLIENT_TABLE_SYNC { get; set; }
        public virtual DbSet<ST_CUSTOMER_ADDITIONAL> ST_CUSTOMER_ADDITIONAL { get; set; }
        public virtual DbSet<ST_GL_MAPPING_ACCOUNT_SETTINGS> ST_GL_MAPPING_ACCOUNT_SETTINGS { get; set; }
        public virtual DbSet<ST_GL_MAPPING_ACCOUNT_TYPE> ST_GL_MAPPING_ACCOUNT_TYPE { get; set; }
        public virtual DbSet<ST_GL_MAPPING_COUNTRY> ST_GL_MAPPING_COUNTRY { get; set; }
        public virtual DbSet<ST_GL_MAPPING_COVERAGE> ST_GL_MAPPING_COVERAGE { get; set; }
        public virtual DbSet<ST_GL_MAPPING_LINE_OF_BUSINESS> ST_GL_MAPPING_LINE_OF_BUSINESS { get; set; }
        public virtual DbSet<ST_GL_MAPPING_POLICY_TYPE> ST_GL_MAPPING_POLICY_TYPE { get; set; }
        public virtual DbSet<ST_GL_MAPPING_VEHICLE_TYPE> ST_GL_MAPPING_VEHICLE_TYPE { get; set; }
        public virtual DbSet<ST_GL_MAPPING_ZONE> ST_GL_MAPPING_ZONE { get; set; }
        public virtual DbSet<ST_ITEM_SALESPERSON_COMMISSION> ST_ITEM_SALESPERSON_COMMISSION { get; set; }
        public virtual DbSet<ST_POLICY_TABLE_SYNC> ST_POLICY_TABLE_SYNC { get; set; }
        public virtual DbSet<ST_TRANSACTION_SYNC> ST_TRANSACTION_SYNC { get; set; }
        public virtual DbSet<RM00201> RM00201 { get; set; }
        public virtual DbSet<IV00101> IV00101 { get; set; }
        public virtual DbSet<RM00101> RM00101 { get; set; }
        public virtual DbSet<ST_GL_MAPPING_SUPERVISOR> ST_GL_MAPPING_SUPERVISOR { get; set; }
        public virtual DbSet<ST_GL_MAPPING_REINSURANCE> ST_GL_MAPPING_REINSURANCE { get; set; }
        public virtual DbSet<RM00301> RM00301 { get; set; }
        public virtual DbSet<ST_SYSFLEX_POLICY_RENEW> ST_SYSFLEX_POLICY_RENEW { get; set; }
        public virtual DbSet<ST_GL_MAPPING_CHANNEL> ST_GL_MAPPING_CHANNEL { get; set; }
        public virtual DbSet<ST_ITEMNMBR_ACCOUNT_CODE> ST_ITEMNMBR_ACCOUNT_CODE { get; set; }
        public virtual DbSet<ST_ITEM_CHANNEL_COMMISSION> ST_ITEM_CHANNEL_COMMISSION { get; set; }
        public virtual DbSet<ST_CHANNEL_NO_COMMISSION> ST_CHANNEL_NO_COMMISSION { get; set; }
        public virtual DbSet<ST_SYSFLEX_POLICY_RENEW_NC> ST_SYSFLEX_POLICY_RENEW_NC { get; set; }
    
        public virtual ObjectResult<string> usp_ST_SYSFLEX_CUSTOMER_GET_CLASS(string lINE_OF_BUSINESS, string pOLICY_TYPE, string vEHICLE_TYPE, string zONE, string cOUNTRY, string cHANNEL, string sUPERVISOR, string gPProductID)
        {
            var lINE_OF_BUSINESSParameter = lINE_OF_BUSINESS != null ?
                new ObjectParameter("LINE_OF_BUSINESS", lINE_OF_BUSINESS) :
                new ObjectParameter("LINE_OF_BUSINESS", typeof(string));
    
            var pOLICY_TYPEParameter = pOLICY_TYPE != null ?
                new ObjectParameter("POLICY_TYPE", pOLICY_TYPE) :
                new ObjectParameter("POLICY_TYPE", typeof(string));
    
            var vEHICLE_TYPEParameter = vEHICLE_TYPE != null ?
                new ObjectParameter("VEHICLE_TYPE", vEHICLE_TYPE) :
                new ObjectParameter("VEHICLE_TYPE", typeof(string));
    
            var zONEParameter = zONE != null ?
                new ObjectParameter("ZONE", zONE) :
                new ObjectParameter("ZONE", typeof(string));
    
            var cOUNTRYParameter = cOUNTRY != null ?
                new ObjectParameter("COUNTRY", cOUNTRY) :
                new ObjectParameter("COUNTRY", typeof(string));
    
            var cHANNELParameter = cHANNEL != null ?
                new ObjectParameter("CHANNEL", cHANNEL) :
                new ObjectParameter("CHANNEL", typeof(string));
    
            var sUPERVISORParameter = sUPERVISOR != null ?
                new ObjectParameter("SUPERVISOR", sUPERVISOR) :
                new ObjectParameter("SUPERVISOR", typeof(string));
    
            var gPProductIDParameter = gPProductID != null ?
                new ObjectParameter("GPProductID", gPProductID) :
                new ObjectParameter("GPProductID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ST_SYSFLEX_CUSTOMER_GET_CLASS", lINE_OF_BUSINESSParameter, pOLICY_TYPEParameter, vEHICLE_TYPEParameter, zONEParameter, cOUNTRYParameter, cHANNELParameter, sUPERVISORParameter, gPProductIDParameter);
        }
    
        public virtual ObjectResult<SYSFLEX_CUSTOMER> usp_ST_SYSFLEX_CUSTOMER_GET_PARENTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYSFLEX_CUSTOMER>("usp_ST_SYSFLEX_CUSTOMER_GET_PARENTS");
        }
    
        public virtual ObjectResult<SYSFLEX_POLICY> usp_ST_SYSFLEX_CUSTOMER_GET_POLICY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYSFLEX_POLICY>("usp_ST_SYSFLEX_CUSTOMER_GET_POLICY");
        }
    
        public virtual ObjectResult<SYSFLEX_POLICY> usp_ST_SYSFLEX_CUSTOMER_GET_POLICY_INFO(string pOLICY_NUMBER)
        {
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYSFLEX_POLICY>("usp_ST_SYSFLEX_CUSTOMER_GET_POLICY_INFO", pOLICY_NUMBERParameter);
        }
    
        public virtual int usp_ST_SYSFLEX_GET_COVERAGE_DISTRIB(string pOLICY_NUMBER, string tRANS_TYPE)
        {
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            var tRANS_TYPEParameter = tRANS_TYPE != null ?
                new ObjectParameter("TRANS_TYPE", tRANS_TYPE) :
                new ObjectParameter("TRANS_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ST_SYSFLEX_GET_COVERAGE_DISTRIB", pOLICY_NUMBERParameter, tRANS_TYPEParameter);
        }
    
        public virtual ObjectResult<TRANSACTION_BY_COVERAGE> usp_ST_SYSFLEX_GET_TRANSACTION_BY_COVERAGE(string pOLICY_NUMBER, Nullable<int> transaction_Secuence)
        {
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            var transaction_SecuenceParameter = transaction_Secuence.HasValue ?
                new ObjectParameter("Transaction_Secuence", transaction_Secuence) :
                new ObjectParameter("Transaction_Secuence", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRANSACTION_BY_COVERAGE>("usp_ST_SYSFLEX_GET_TRANSACTION_BY_COVERAGE", pOLICY_NUMBERParameter, transaction_SecuenceParameter);
        }
    
        public virtual ObjectResult<TRANSACTION_INVOICE> usp_ST_SYSFLEX_GET_TRANSACTIONS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRANSACTION_INVOICE>("usp_ST_SYSFLEX_GET_TRANSACTIONS");
        }
    
        public virtual ObjectResult<SYSFLEX_CUSTOMER> usp_ST_SYSFLEX_POLICY_GET_PARENT(Nullable<int> cLIENTID)
        {
            var cLIENTIDParameter = cLIENTID.HasValue ?
                new ObjectParameter("CLIENTID", cLIENTID) :
                new ObjectParameter("CLIENTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYSFLEX_CUSTOMER>("usp_ST_SYSFLEX_POLICY_GET_PARENT", cLIENTIDParameter);
        }
    
        public virtual int usp_ST_SYSFLEX_INSERT_TRANSACTIONS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ST_SYSFLEX_INSERT_TRANSACTIONS");
        }
    
        public virtual ObjectResult<SYSFLEX_REINSURANCE_BY_COVERAGE> usp_ST_SYSFLEX_GET_REINSURANCE_BY_COVERAGE(string cUSTNMBR, Nullable<int> transaction_Secuence)
        {
            var cUSTNMBRParameter = cUSTNMBR != null ?
                new ObjectParameter("CUSTNMBR", cUSTNMBR) :
                new ObjectParameter("CUSTNMBR", typeof(string));
    
            var transaction_SecuenceParameter = transaction_Secuence.HasValue ?
                new ObjectParameter("Transaction_Secuence", transaction_Secuence) :
                new ObjectParameter("Transaction_Secuence", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYSFLEX_REINSURANCE_BY_COVERAGE>("usp_ST_SYSFLEX_GET_REINSURANCE_BY_COVERAGE", cUSTNMBRParameter, transaction_SecuenceParameter);
        }
    
        public virtual int usp_ST_SYSFLEX_UPDATE_TRANSACTION_SYNC(Nullable<int> dOCTYPE, string mODULE, string pOLICY_NUMBER, Nullable<int> tRANSACTION_SEQUENCE)
        {
            var dOCTYPEParameter = dOCTYPE.HasValue ?
                new ObjectParameter("DOCTYPE", dOCTYPE) :
                new ObjectParameter("DOCTYPE", typeof(int));
    
            var mODULEParameter = mODULE != null ?
                new ObjectParameter("MODULE", mODULE) :
                new ObjectParameter("MODULE", typeof(string));
    
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            var tRANSACTION_SEQUENCEParameter = tRANSACTION_SEQUENCE.HasValue ?
                new ObjectParameter("TRANSACTION_SEQUENCE", tRANSACTION_SEQUENCE) :
                new ObjectParameter("TRANSACTION_SEQUENCE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ST_SYSFLEX_UPDATE_TRANSACTION_SYNC", dOCTYPEParameter, mODULEParameter, pOLICY_NUMBERParameter, tRANSACTION_SEQUENCEParameter);
        }
    
        public virtual int pSP_CREAR_CUENTAS(string aCTNUMST, string aCTDESCR, Nullable<int> tPCLBLNC, Nullable<int> pSTNGTYP, Nullable<int> aCCTTYPE, string cATEGORY, Nullable<int> dECPLACS)
        {
            var aCTNUMSTParameter = aCTNUMST != null ?
                new ObjectParameter("ACTNUMST", aCTNUMST) :
                new ObjectParameter("ACTNUMST", typeof(string));
    
            var aCTDESCRParameter = aCTDESCR != null ?
                new ObjectParameter("ACTDESCR", aCTDESCR) :
                new ObjectParameter("ACTDESCR", typeof(string));
    
            var tPCLBLNCParameter = tPCLBLNC.HasValue ?
                new ObjectParameter("TPCLBLNC", tPCLBLNC) :
                new ObjectParameter("TPCLBLNC", typeof(int));
    
            var pSTNGTYPParameter = pSTNGTYP.HasValue ?
                new ObjectParameter("PSTNGTYP", pSTNGTYP) :
                new ObjectParameter("PSTNGTYP", typeof(int));
    
            var aCCTTYPEParameter = aCCTTYPE.HasValue ?
                new ObjectParameter("ACCTTYPE", aCCTTYPE) :
                new ObjectParameter("ACCTTYPE", typeof(int));
    
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var dECPLACSParameter = dECPLACS.HasValue ?
                new ObjectParameter("DECPLACS", dECPLACS) :
                new ObjectParameter("DECPLACS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pSP_CREAR_CUENTAS", aCTNUMSTParameter, aCTDESCRParameter, tPCLBLNCParameter, pSTNGTYPParameter, aCCTTYPEParameter, cATEGORYParameter, dECPLACSParameter);
        }
    
        public virtual int usp_SYSFLEX_CHANGE_STATE_CUSTOMER(string cUSTNMBR, Nullable<byte> sTATUS)
        {
            var cUSTNMBRParameter = cUSTNMBR != null ?
                new ObjectParameter("CUSTNMBR", cUSTNMBR) :
                new ObjectParameter("CUSTNMBR", typeof(string));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SYSFLEX_CHANGE_STATE_CUSTOMER", cUSTNMBRParameter, sTATUSParameter);
        }
    
        public virtual int usp_SYSFLEX_DELETE_RESERVE(string sOPNUMBE)
        {
            var sOPNUMBEParameter = sOPNUMBE != null ?
                new ObjectParameter("SOPNUMBE", sOPNUMBE) :
                new ObjectParameter("SOPNUMBE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SYSFLEX_DELETE_RESERVE", sOPNUMBEParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> usp_ST_GL_VERIFY_ACCOUNT_EXISTS(string aCTNUMST)
        {
            var aCTNUMSTParameter = aCTNUMST != null ?
                new ObjectParameter("ACTNUMST", aCTNUMST) :
                new ObjectParameter("ACTNUMST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("usp_ST_GL_VERIFY_ACCOUNT_EXISTS", aCTNUMSTParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> usp_ST_SYSFLEX_GET_RENEW_DATES(Nullable<int> yEAR, Nullable<int> mONTH)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            var mONTHParameter = mONTH.HasValue ?
                new ObjectParameter("MONTH", mONTH) :
                new ObjectParameter("MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("usp_ST_SYSFLEX_GET_RENEW_DATES", yEARParameter, mONTHParameter);
        }
    
        public virtual ObjectResult<string> usp_ST_SYSFLEX_GET_RENEW_INVOICES(Nullable<System.DateTime> iNITIAL_DATE)
        {
            var iNITIAL_DATEParameter = iNITIAL_DATE.HasValue ?
                new ObjectParameter("INITIAL_DATE", iNITIAL_DATE) :
                new ObjectParameter("INITIAL_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_ST_SYSFLEX_GET_RENEW_INVOICES", iNITIAL_DATEParameter);
        }
    
        public virtual ObjectResult<POSTING_DITRIBUTION> usp_SYSFLEX_GET_POSTING_DITRIBUTION(string sOPNUMBE)
        {
            var sOPNUMBEParameter = sOPNUMBE != null ?
                new ObjectParameter("SOPNUMBE", sOPNUMBE) :
                new ObjectParameter("SOPNUMBE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<POSTING_DITRIBUTION>("usp_SYSFLEX_GET_POSTING_DITRIBUTION", sOPNUMBEParameter);
        }
    
        public virtual ObjectResult<UNIT_DISTRIBUTION> usp_SYSFLEX_GET_UNIT_DISTRIBUTION(string sOPNUMBE)
        {
            var sOPNUMBEParameter = sOPNUMBE != null ?
                new ObjectParameter("SOPNUMBE", sOPNUMBE) :
                new ObjectParameter("SOPNUMBE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UNIT_DISTRIBUTION>("usp_SYSFLEX_GET_UNIT_DISTRIBUTION", sOPNUMBEParameter);
        }
    
        public virtual int usp_SYSFLEX_RENEW_UPDATE_STATE(Nullable<System.DateTime> iNITIAL_DATE)
        {
            var iNITIAL_DATEParameter = iNITIAL_DATE.HasValue ?
                new ObjectParameter("INITIAL_DATE", iNITIAL_DATE) :
                new ObjectParameter("INITIAL_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SYSFLEX_RENEW_UPDATE_STATE", iNITIAL_DATEParameter);
        }
    
        public virtual int usp_ST_SYSFLEX_UPDATE_COMMISSION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ST_SYSFLEX_UPDATE_COMMISSION");
        }
    }
}
