//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM00201
    {
        public string CLASSID { get; set; }
        public string CLASDSCR { get; set; }
        public short CRLMTTYP { get; set; }
        public decimal CRLMTAMT { get; set; }
        public short CRLMTPER { get; set; }
        public decimal CRLMTPAM { get; set; }
        public byte DEFLTCLS { get; set; }
        public short BALNCTYP { get; set; }
        public string CHEKBKID { get; set; }
        public string BANKNAME { get; set; }
        public string TAXSCHID { get; set; }
        public string SHIPMTHD { get; set; }
        public string PYMTRMID { get; set; }
        public short CUSTDISC { get; set; }
        public string CSTPRLVL { get; set; }
        public short MINPYTYP { get; set; }
        public decimal MINPYDLR { get; set; }
        public short MINPYPCT { get; set; }
        public short MXWOFTYP { get; set; }
        public decimal MXWROFAM { get; set; }
        public byte FINCHARG { get; set; }
        public short FNCHATYP { get; set; }
        public decimal FINCHDLR { get; set; }
        public short FNCHPCNT { get; set; }
        public string PRCLEVEL { get; set; }
        public string CURNCYID { get; set; }
        public string RATETPID { get; set; }
        public short DEFCACTY { get; set; }
        public int RMCSHACC { get; set; }
        public int RMARACC { get; set; }
        public int RMCOSACC { get; set; }
        public int RMIVACC { get; set; }
        public int RMSLSACC { get; set; }
        public int RMAVACC { get; set; }
        public int RMTAKACC { get; set; }
        public int RMFCGACC { get; set; }
        public int RMWRACC { get; set; }
        public int RMSORACC { get; set; }
        public string SALSTERR { get; set; }
        public string SLPRSNID { get; set; }
        public short STMTCYCL { get; set; }
        public byte SNDSTMNT { get; set; }
        public byte INACTIVE { get; set; }
        public byte KPCALHST { get; set; }
        public byte KPDSTHST { get; set; }
        public byte KPERHIST { get; set; }
        public byte KPTRXHST { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public byte Revalue_Customer { get; set; }
        public short Post_Results_To { get; set; }
        public short DISGRPER { get; set; }
        public short DUEGRPER { get; set; }
        public short ORDERFULFILLDEFAULT { get; set; }
        public short CUSTPRIORITY { get; set; }
        public int RMOvrpymtWrtoffAcctIdx { get; set; }
        public byte CBVAT { get; set; }
        public byte INCLUDEINDP { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
