//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CUSTOMER_ADDITIONAL
    {
        public string CUSTNMBR { get; set; }
        public string ZONE { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string POLICY_TYPE { get; set; }
        public string POLICY_NUMBER { get; set; }
        public Nullable<int> COUNT_VEHICLE { get; set; }
        public Nullable<System.DateTime> INITAL_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string SUPERVISOR { get; set; }
        public Nullable<short> AGENT_ID { get; set; }
        public string AGENT_CODE { get; set; }
        public string AGENT { get; set; }
        public Nullable<decimal> MPV_total_bruto { get; set; }
        public Nullable<decimal> MPV_Descuento_flota { get; set; }
        public Nullable<decimal> MPV_Descuento_Experiencia { get; set; }
        public Nullable<decimal> MPV_ITBIS { get; set; }
        public string POLICY_STATUS { get; set; }
        public string CREATED_USER { get; set; }
        public string MODIFIED_USER { get; set; }
        public string COMMENT { get; set; }
        public string CHANNEL { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> CORE_CREATION_DATE { get; set; }
        public Nullable<System.DateTime> POLICY_CANCELLATION_DATE { get; set; }
        public Nullable<decimal> INSURED_QUANTITY { get; set; }
    }
}
