//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_GL_MAPPING_ACCOUNT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ST_GL_MAPPING_ACCOUNT_TYPE()
        {
            this.ST_GL_MAPPING_ACCOUNT_SETTINGS = new HashSet<ST_GL_MAPPING_ACCOUNT_SETTINGS>();
        }
    
        public int TYPEID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_GL_MAPPING_ACCOUNT_SETTINGS> ST_GL_MAPPING_ACCOUNT_SETTINGS { get; set; }
    }
}
