//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_GL_MAPPING_VEHICLE_TYPE
    {
        public string VEHICLE_TYPE { get; set; }
        public string GL_MAPPING { get; set; }
    }
}
