//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_GL_MAPPING_ACCOUNT_SETTINGS
    {
        public long ROW_ID { get; set; }
        public int TYPEID { get; set; }
        public string SEGMENT1 { get; set; }
        public string SEGMENT2 { get; set; }
        public string LINE_OF_BUSINESS { get; set; }
        public string PRODUCT { get; set; }
        public string UNIT_ACCOUNT1 { get; set; }
        public string UNIT_ACCOUNT2 { get; set; }
        public string UNIT_ACCOUNT3 { get; set; }
    
        public virtual ST_GL_MAPPING_ACCOUNT_TYPE ST_GL_MAPPING_ACCOUNT_TYPE { get; set; }
    }
}
