//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ITEMNMBR_ACCOUNT_CODE
    {
        public string ITEMNMBR { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public int ROW_ID { get; set; }
    }
}
