//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ITEM_SALESPERSON_COMMISSION
    {
        public long ROW_ID { get; set; }
        public string SLPRSNID { get; set; }
        public string ITEMNMBR { get; set; }
        public decimal COMMISSION_PERCENT { get; set; }
    }
}
