//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_POLICY_TABLE_SYNC
    {
        public string POLICY_NUMBER { get; set; }
        public Nullable<System.DateTime> LAST_GP_UPDATE { get; set; }
    }
}
