//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class SYSFLEX_CUSTOMER
    {
        public Nullable<decimal> CUSTNMBR { get; set; }
        public Nullable<int> CPRCSTNM { get; set; }
        public Nullable<int> HOLD { get; set; }
        public Nullable<byte> INACTIVE { get; set; }
        public string CUSTNAME { get; set; }
        public string SHRTNAME { get; set; }
        public string STMTNAME { get; set; }
        public string CUSTCLAS { get; set; }
        public Nullable<int> CUSTPRIORITY { get; set; }
        public Nullable<int> ADRSCODE { get; set; }
        public string CNTCPRSN { get; set; }
        public string ADDRESS1 { get; set; }
        public Nullable<int> ADDRESS2 { get; set; }
        public Nullable<int> ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<int> ZIPCODE { get; set; }
        public Nullable<int> CCode { get; set; }
        public string COUNTRY { get; set; }
        public string PHNUMBR1 { get; set; }
        public string PHNUMBR2 { get; set; }
        public string PHNUMBR3 { get; set; }
        public string fax { get; set; }
        public Nullable<int> UPSZONE { get; set; }
        public Nullable<int> SHIPMTHD { get; set; }
        public Nullable<int> TAXSCHID { get; set; }
        public Nullable<int> SHIPCOMPLETE { get; set; }
        public Nullable<int> PRSTADCD { get; set; }
        public Nullable<int> PRBTADCD { get; set; }
        public Nullable<int> STADDRCD { get; set; }
        public Nullable<int> SLPRSNID { get; set; }
        public Nullable<int> SALSTERR { get; set; }
        public Nullable<int> USERDEF1 { get; set; }
        public Nullable<int> USERDEF2 { get; set; }
        public Nullable<int> COMMENT1 { get; set; }
        public Nullable<int> COMMENT2 { get; set; }
        public Nullable<int> CUSTDISC { get; set; }
        public Nullable<int> PYMTRMID { get; set; }
        public Nullable<int> DISGRPER { get; set; }
        public Nullable<int> DUEGRPER { get; set; }
        public Nullable<int> PRCLEVEL { get; set; }
        public Nullable<int> NOTETEXT { get; set; }
        public Nullable<int> BALNCTYP { get; set; }
        public Nullable<int> FNCHATYP { get; set; }
        public Nullable<int> FNCHPCNT { get; set; }
        public Nullable<int> FINCHDLR { get; set; }
        public Nullable<int> MINPYTYP { get; set; }
        public Nullable<int> MINPYPCT { get; set; }
        public Nullable<int> MINPYDLR { get; set; }
        public Nullable<int> CRLMTTYP { get; set; }
        public Nullable<int> CRLMTAMT { get; set; }
        public Nullable<int> CRLMTPER { get; set; }
        public Nullable<int> CRLMTPAM { get; set; }
        public Nullable<int> MXWOFTYP { get; set; }
        public Nullable<int> MXWROFAM { get; set; }
        public Nullable<int> Revalue_Customer { get; set; }
        public Nullable<int> Post_Results_To { get; set; }
        public Nullable<int> ORDERFULFILLDEFAULT { get; set; }
        public Nullable<int> INCLUDEINDP { get; set; }
        public Nullable<int> CRCARDID { get; set; }
        public Nullable<int> CRCRDNUM { get; set; }
        public Nullable<int> CCRDXPDT { get; set; }
        public Nullable<int> BANKNAME { get; set; }
        public Nullable<int> BNKBRNCH { get; set; }
        public Nullable<int> USERLANG { get; set; }
        public Nullable<int> TAXEXMT1 { get; set; }
        public Nullable<int> TAXEXMT2 { get; set; }
        public Nullable<int> TXRGNNUM { get; set; }
        public Nullable<int> CURNCYID { get; set; }
        public Nullable<int> RATETPID { get; set; }
        public Nullable<int> STMTCYCL { get; set; }
        public Nullable<int> KPCALHST { get; set; }
        public Nullable<int> KPERHIST { get; set; }
        public Nullable<int> KPTRXHST { get; set; }
        public Nullable<int> KPDSTHST { get; set; }
        public Nullable<int> Send_Email_Statements { get; set; }
        public Nullable<int> ToEmail_Recipient { get; set; }
        public Nullable<int> CcEmail_Recipient { get; set; }
        public Nullable<int> BccEmail_Recipient { get; set; }
        public Nullable<int> CHEKBKID { get; set; }
        public Nullable<int> DEFCACTY { get; set; }
        public Nullable<int> RMCSHACTNUMST { get; set; }
        public Nullable<int> RMARACTNUMST { get; set; }
        public Nullable<int> RMSLSACTNUMST { get; set; }
        public Nullable<int> RMCOSACTNUMST { get; set; }
        public Nullable<int> RMIVACTNUMST { get; set; }
        public Nullable<int> RMTAKACTNUMST { get; set; }
        public Nullable<int> RMAVACTNUMST { get; set; }
        public Nullable<int> RMFCGACTNUMST { get; set; }
        public Nullable<int> RMWRACTNUMST { get; set; }
        public Nullable<int> RMSORACTNUMST { get; set; }
        public Nullable<int> RMOvrpymtWrtoffACTNUMST { get; set; }
        public Nullable<int> GPSFOINTEGRATIONID { get; set; }
        public Nullable<int> INTEGRATIONSOURCE { get; set; }
        public Nullable<int> INTEGRATIONID { get; set; }
        public string INET1 { get; set; }
        public Nullable<System.DateTime> SYSTEMCREATEDDATE { get; set; }
        public Nullable<System.DateTime> TRGCREATEDDATE { get; set; }
        public Nullable<System.DateTime> TRGMODIFIEDDATE { get; set; }
        public Nullable<int> Ubicacion { get; set; }
        public Nullable<int> NCF_TYPE { get; set; }
        public string ID { get; set; }
        public string ID_TYPE { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
    }
}
