//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class SYSFLEX_TRANSACTIONS
    {
        public string POLICYNUMBER { get; set; }
        public string TRANS_TYPE { get; set; }
        public string TRANS_DESC { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public int DOCUMENT_TYPE { get; set; }
        public string DOCUMENT_CANCELED { get; set; }
        public Nullable<decimal> ACTUAL_BALANCE { get; set; }
        public string COMMENT { get; set; }
        public string USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string NCF { get; set; }
        public string NCF_GP_TYPE { get; set; }
        public Nullable<byte> NCF_SYSFLEX_TYPE { get; set; }
        public string GP_DOCUMENT_NUMBER { get; set; }
        public Nullable<int> Policy_Transaction_secuence { get; set; }
    }
}
