//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class SYSFLEX_REINSURANCE_BY_COVERAGE
    {
        public string POLICY_NUMBER { get; set; }
        public string TRANS_TYPE { get; set; }
        public Nullable<int> Item_number { get; set; }
        public Nullable<decimal> TRANS_AMOUNT { get; set; }
        public Nullable<decimal> Trans_Tax_Amount { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string Product_type { get; set; }
        public string Coverage_Desc { get; set; }
        public Nullable<int> Coverage_ID { get; set; }
        public Nullable<decimal> Coverage_Limit { get; set; }
        public string Coverage_Group { get; set; }
        public Nullable<decimal> Coverage_Amount { get; set; }
        public Nullable<decimal> Coverage_Percent { get; set; }
        public decimal Reinsurance_Percent_Commission { get; set; }
        public Nullable<decimal> Reinsurance_Amount_Commission { get; set; }
        public int Policy_Transaction_secuence { get; set; }
        public int Company { get; set; }
        public string Name_Company { get; set; }
        public string Type_identifierr { get; set; }
        public string Number_Identifierr { get; set; }
        public string Number_Contrat { get; set; }
        public string Type_Contrat { get; set; }
        public int Company_is_Local { get; set; }
    }
}
