//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class SYSFLEX_POLICY
    {
        public string LINE_OF_BUSINESS { get; set; }
        public string ZONE { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string POLICY_TYPE { get; set; }
        public string POLICY_NUMBER { get; set; }
        public int COUNT_VEHICLE { get; set; }
        public Nullable<System.DateTime> INITAL_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<decimal> CLIENT_ID { get; set; }
        public string SUPERVISOR { get; set; }
        public Nullable<int> AGENT_ID { get; set; }
        public Nullable<int> AGENT_CODE { get; set; }
        public string AGENT { get; set; }
        public string CHANNEL { get; set; }
        public Nullable<decimal> MPV_total_bruto { get; set; }
        public decimal MPV_Descuento_flota { get; set; }
        public Nullable<decimal> MPV_Descuento_Experiencia { get; set; }
        public Nullable<decimal> MPV_ITBIS { get; set; }
        public string POLICY_STATUS { get; set; }
        public string CREATED_USER { get; set; }
        public string MODIFIED_USER { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string GpProductID { get; set; }
        public int In_Coaseguro { get; set; }
        public int Primary_Company { get; set; }
        public Nullable<int> SUPERVISOR_CODE { get; set; }
    }
}
