//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    
    public partial class TRANSACTION_BY_COVERAGE
    {
        public string POLICY_NUMBER { get; set; }
        public string TRANS_TYPE { get; set; }
        public string TRANS_DESC { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public Nullable<decimal> TRANS_AMOUNT { get; set; }
        public Nullable<decimal> Trans_Tax_Amount { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string Product_type { get; set; }
        public string Coverage_Desc { get; set; }
        public string Coverage_Group { get; set; }
        public Nullable<decimal> Coverage_Amount { get; set; }
        public int Policy_Transaction_secuence { get; set; }
    }
}
